var annotated_dup =
[
    [ "aatc_container_base", "classaatc__container__base.html", "classaatc__container__base" ],
    [ "aatc_container_list_template", "classaatc__container__list__template.html", "classaatc__container__list__template" ],
    [ "aatc_container_list_tempspec", "classaatc__container__list__tempspec.html", "classaatc__container__list__tempspec" ],
    [ "aatc_container_map_template", "classaatc__container__map__template.html", "classaatc__container__map__template" ],
    [ "aatc_container_set_template", "classaatc__container__set__template.html", "classaatc__container__set__template" ],
    [ "aatc_container_set_tempspec", "classaatc__container__set__tempspec.html", "classaatc__container__set__tempspec" ],
    [ "aatc_container_shared_1tp_template", "classaatc__container__shared__1tp__template.html", "classaatc__container__shared__1tp__template" ],
    [ "aatc_container_shared_1tp_tempspec", "classaatc__container__shared__1tp__tempspec.html", "classaatc__container__shared__1tp__tempspec" ],
    [ "aatc_container_shared_map_template", "classaatc__container__shared__map__template.html", "classaatc__container__shared__map__template" ],
    [ "aatc_container_traits_1tp_base", "classaatc__container__traits__1tp__base.html", "classaatc__container__traits__1tp__base" ],
    [ "aatc_container_traits_list", "classaatc__container__traits__list.html", "classaatc__container__traits__list" ],
    [ "aatc_container_traits_set", "classaatc__container__traits__set.html", "classaatc__container__traits__set" ],
    [ "aatc_container_traits_unordered_set", "classaatc__container__traits__unordered__set.html", "classaatc__container__traits__unordered__set" ],
    [ "aatc_container_traits_vector", "classaatc__container__traits__vector.html", "classaatc__container__traits__vector" ],
    [ "aatc_container_unordered_map_template", "classaatc__container__unordered__map__template.html", "classaatc__container__unordered__map__template" ],
    [ "aatc_container_unordered_set_template", "classaatc__container__unordered__set__template.html", "classaatc__container__unordered__set__template" ],
    [ "aatc_container_unordered_set_tempspec", "classaatc__container__unordered__set__tempspec.html", "classaatc__container__unordered__set__tempspec" ],
    [ "aatc_container_vector_template", "classaatc__container__vector__template.html", "classaatc__container__vector__template" ],
    [ "aatc_container_vector_tempspec", "classaatc__container__vector__tempspec.html", "classaatc__container__vector__tempspec" ],
    [ "aatc_containerfunctor_comp", "classaatc__containerfunctor__comp.html", "classaatc__containerfunctor__comp" ],
    [ "aatc_containerfunctor_equals", "classaatc__containerfunctor__equals.html", "classaatc__containerfunctor__equals" ],
    [ "aatc_containerfunctor_hash", "classaatc__containerfunctor__hash.html", "classaatc__containerfunctor__hash" ],
    [ "aatc_containerfunctor_map_comp", "classaatc__containerfunctor__map__comp.html", "classaatc__containerfunctor__map__comp" ],
    [ "aatc_containerfunctor_map_equals", "classaatc__containerfunctor__map__equals.html", "classaatc__containerfunctor__map__equals" ],
    [ "aatc_containerfunctor_map_hash", "classaatc__containerfunctor__map__hash.html", "classaatc__containerfunctor__map__hash" ],
    [ "aatc_containerfunctor_map_Settings", "classaatc__containerfunctor__map___settings.html", "classaatc__containerfunctor__map___settings" ],
    [ "aatc_containerfunctor_Settings", "classaatc__containerfunctor___settings.html", "classaatc__containerfunctor___settings" ],
    [ "aatc_containertype_specific_storage", "classaatc__containertype__specific__storage.html", "classaatc__containertype__specific__storage" ],
    [ "aatc_engine_level_storage", "classaatc__engine__level__storage.html", "classaatc__engine__level__storage" ],
    [ "aatc_functor_hash", "classaatc__functor__hash.html", "classaatc__functor__hash" ],
    [ "aatc_functor_hash< aatc_type_float32 >", "classaatc__functor__hash_3_01aatc__type__float32_01_4.html", "classaatc__functor__hash_3_01aatc__type__float32_01_4" ],
    [ "aatc_functor_hash< aatc_type_float64 >", "classaatc__functor__hash_3_01aatc__type__float64_01_4.html", "classaatc__functor__hash_3_01aatc__type__float64_01_4" ],
    [ "aatc_functor_hash< aatc_type_string >", "classaatc__functor__hash_3_01aatc__type__string_01_4.html", "classaatc__functor__hash_3_01aatc__type__string_01_4" ],
    [ "aatc_info_container_list", "classaatc__info__container__list.html", "classaatc__info__container__list" ],
    [ "aatc_info_container_map", "classaatc__info__container__map.html", "classaatc__info__container__map" ],
    [ "aatc_info_container_set", "classaatc__info__container__set.html", "classaatc__info__container__set" ],
    [ "aatc_info_container_unordered_map", "classaatc__info__container__unordered__map.html", "classaatc__info__container__unordered__map" ],
    [ "aatc_info_container_unordered_set", "classaatc__info__container__unordered__set.html", "classaatc__info__container__unordered__set" ],
    [ "aatc_info_container_vector", "classaatc__info__container__vector.html", "classaatc__info__container__vector" ],
    [ "aatc_Initializer", "classaatc___initializer.html", "classaatc___initializer" ],
    [ "aatc_Initializer_tm_iterate_register_all_containers", "classaatc___initializer__tm__iterate__register__all__containers.html", "classaatc___initializer__tm__iterate__register__all__containers" ],
    [ "aatc_iterator", "classaatc__iterator.html", "classaatc__iterator" ],
    [ "aatc_iterator_base", "classaatc__iterator__base.html", "classaatc__iterator__base" ],
    [ "aatc_N", "classaatc___n.html", null ],
    [ "aatc_NULLCLASS", "classaatc___n_u_l_l_c_l_a_s_s.html", null ],
    [ "aatc_primunion", "structaatc__primunion.html", "structaatc__primunion" ],
    [ "aatc_refcounted", "classaatc__refcounted.html", "classaatc__refcounted" ],
    [ "aatc_refcounted_GC", "classaatc__refcounted___g_c.html", "classaatc__refcounted___g_c" ],
    [ "aatc_script_Funcpointer", "classaatc__script___funcpointer.html", "classaatc__script___funcpointer" ],
    [ "aatc_std_Spinlock", "classaatc__std___spinlock.html", "classaatc__std___spinlock" ],
    [ "aatc_template_specific_storage", "classaatc__template__specific__storage.html", "classaatc__template__specific__storage" ],
    [ "aatc_tm_iterator_1arg_functor", "classaatc__tm__iterator__1arg__functor.html", "classaatc__tm__iterator__1arg__functor" ],
    [ "aatc_tm_iterator_1arg_functor_actual", "classaatc__tm__iterator__1arg__functor__actual.html", "classaatc__tm__iterator__1arg__functor__actual" ],
    [ "aatc_tm_iterator_1arg_functor_actual< iteration_start, iteration_end,-1, functor_operate, tup_t >", "classaatc__tm__iterator__1arg__functor__actual_3_01iteration__start_00_01iteration__end_00-1_00_6c2e9a8a7ddac5d8518bad12a702d7a7.html", "classaatc__tm__iterator__1arg__functor__actual_3_01iteration__start_00_01iteration__end_00-1_00_6c2e9a8a7ddac5d8518bad12a702d7a7" ],
    [ "aatc_tm_iterator_functor", "classaatc__tm__iterator__functor.html", "classaatc__tm__iterator__functor" ],
    [ "aatc_tm_iterator_functor_actual", "classaatc__tm__iterator__functor__actual.html", "classaatc__tm__iterator__functor__actual" ],
    [ "aatc_tm_iterator_functor_actual< iteration_start, iteration_end,-1, functor_operate >", "classaatc__tm__iterator__functor__actual_3_01iteration__start_00_01iteration__end_00-1_00_01functor__operate_01_4.html", "classaatc__tm__iterator__functor__actual_3_01iteration__start_00_01iteration__end_00-1_00_01functor__operate_01_4" ],
    [ "aatc_Y", "classaatc___y.html", null ]
];